-- Allowance/Charge Identification Code Data Insert Statements
-- Generated from UNECE_AllowanceChargeIdentificationCode_D14A.xsd
-- Total records: 106

INSERT INTO allowance_charge_identification_code (code, name, description, category) VALUES
('1', 'Handling commission', 'Fee for the processing of documentary credit, collection and payment which are charged to the customer.', 'Documentary Credit Commission'),
('2', 'Amendment commission', 'Fee for amendments in documentary credit and collection business (not extensions and increases of documentary credits).', 'Documentary Credit Commission'),
('3', 'Acceptance commission', 'Fee for the acceptance of draft in documentary credit and collection business which are drawn on us (also to be seen as a kind of ''guarantee commission'').', 'Documentary Credit Commission'),
('4', 'Commission for obtaining acceptance', 'Fee for obtaining an acceptance under collections on the basis of ''documents against acceptance''.', 'Documentary Credit Commission'),
('5', 'Commission on delivery', 'Fee for delivery of documents without corresponding payment.', 'Collection Commission'),
('6', 'Advising commission', 'Fee for advising documentary credits (charged also in case of confirmed credits).', 'Documentary Credit Commission'),
('7', 'Confirmation commission', 'Fee for confirmation of credit.', 'Documentary Credit Commission'),
('8', 'Deferred payment commission', 'Fee for the deferred payment period under documentary credits confirmed by bank. This fee are charges for the period from presentation of the document until due date of payment.', 'Documentary Credit Commission'),
('9', 'Commission for taking up documents', 'Fee charged to the foreign bank for the processing of documentary credit.', 'Documentary Credit Commission'),
('10', 'Opening commission', 'Fee for opening revocable documentary credit.', 'Documentary Credit Commission'),
('11', 'Fee for payment under reserve', 'Fee charged to the customer for discrepancies in credit documents in the case of which the bank have to stipulate payment under reserve.', 'Reserve Payment Fee'),
('12', 'Discrepancy fee', 'Fee charged to the foreign bank for discrepancies in credit documents.', 'Discrepancy Fee'),
('13', 'Domicilation commission', 'Fee for the domicilation of bills with the bank.', 'Domiciliation Commission'),
('14', 'Commission for release of goods', 'Commission for the release of goods sent to the bank.', 'Release Commission'),
('15', 'Collection commission', 'Fee for settling collections on the basis of ''documents against payments''.', 'Collection Commission'),
('16', 'Negotiation commission', 'Fee for the purchase of documents under sight credit for the first ten days.', 'Documentary Credit Commission'),
('17', 'Return commission', 'Fee for cheques, bills and collections returned unpaid and/or recalled.', 'Collection Commission'),
('18', 'B/L splitting charges', 'Fee for the splitting of bills of lading.', 'Document Charges'),
('19', 'Trust commission', 'Fee for the handling on a fiduciary basis of imported goods that have been warehoused.', 'Trust Commission'),
('20', 'Transfer commission', 'Fee for the transfer of transferable documentary credits.', 'Documentary Credit Commission'),
('21', 'Commission for opening irrevocable documentary credits', 'Fee for opening irrevocable documentary credits. This fee is a kind of ''Guarantee commission'' as compensation for the commitment into which the bank have entered on the customers behalf; similar to confirmation commission, acceptance commission.', 'Documentary Credit Commission'),
('22', 'Pre-advice commission', 'Fee for the pre-advice of a documentary credit.', 'Documentary Credit Commission'),
('23', 'Supervisory commission', 'Fee for the supervising unconfirmed documentary credits with a deferred payment period.', 'Documentary Credit Commission'),
('24', 'Model charges', 'Fee for decoding telex messages.', 'Other Charges'),
('25', 'Risk commission', 'Commission in addition to the confirmation commission for documentary credits from sensitive countries.', 'Documentary Credit Commission'),
('26', 'Guarantee commission', 'Commission for drawing up guaranties.', 'Other Commission'),
('27', 'Reimbursement commission', 'Fee for reimbursement of, for example, documentary credits.', 'Documentary Credit Commission'),
('28', 'Stamp duty', 'Tax payable on bills in accordance with national bill of exchange legislation.', 'Duty'),
('29', 'Brokerage', 'Brokers commission arising, in trade with foreign currencies.', 'Other'),
('30', 'Bank charges', 'Charges deducted/claimed by other banks involved in the transaction.', 'Other Charges'),
('31', 'Bank charges information', 'Charges not included in the total charge amount i.e. the charges are for information only.', 'Other Charges'),
('32', 'Courier fee', 'Fee for use of courier service.', 'Processing Fee'),
('33', 'Phone fee', 'Fee for use of phone.', 'Processing Fee'),
('34', 'Postage fee', 'Fee for postage.', 'Processing Fee'),
('35', 'S.W.I.F.T. fee', 'Fee for use of S.W.I.F.T.', 'Processing Fee'),
('36', 'Telex fee', 'Fee for telex.', 'Processing Fee'),
('37', 'Penalty for late delivery of documents', 'Penalty imposed when documents are delivered late.', 'Penalty'),
('38', 'Penalty for late delivery of valuation of works', 'Penalty imposed when valuation of works is delivered late.', 'Penalty'),
('39', 'Penalty for execution of works behind schedule', 'Penalty imposed when the execution of works is behind schedule.', 'Penalty'),
('40', 'Other penalties', 'Penalty imposed for other reasons.', 'Other'),
('41', 'Bonus for works ahead of schedule', 'Bonus for completing work ahead of schedule.', 'Bonus'),
('42', 'Other bonus', 'Bonus earned for other reasons.', 'Bonus'),
('44', 'Project management cost', 'Cost for project management.', 'Other'),
('45', 'Pro rata retention', 'Proportional retention charge.', 'Other'),
('46', 'Contractual retention', 'Contractual retention charge.', 'Other'),
('47', 'Other retentions', 'Retention charge not otherwise specified.', 'Other'),
('48', 'Interest on arrears', 'Interest for late payment.', 'Other'),
('49', 'Interest', 'Cost of using money.', 'Other'),
('50', 'Charge per credit cover', 'Unit charge per credit cover established.', 'Other Charges'),
('51', 'Charge per unused credit cover', 'Unit charge per unused credit cover.', 'Other Charges'),
('52', 'Minimum commission', 'Minimum commission charge.', 'Other Commission'),
('53', 'Factoring commission', 'Commission charged for factoring services.', 'Other Commission'),
('54', 'Chamber of commerce charge', 'Identifies the charges from the chamber of commerce.', 'Other Charges'),
('55', 'Transfer charges', 'Charges for transfer.', 'Other Charges'),
('56', 'Repatriation charges', 'Charges for repatriation.', 'Other Charges'),
('57', 'Miscellaneous charges', 'Not specifically defined charges.', 'Other Charges'),
('58', 'Foreign exchange charges', 'Charges for foreign exchange.', 'Other Charges'),
('59', 'Agreed debit interest charge', 'Charge for agreed debit interest', 'Other Charges'),
('60', 'Manufacturer''s consumer discount', 'A discount given by the manufacturer which should be passed on to the consumer.', 'Discount'),
('61', 'Fax advice charge', 'Charge for fax advice.', 'Other Charges'),
('62', 'Due to military status', 'Allowance granted because of the military status.', 'Other'),
('63', 'Due to work accident', 'Allowance granted to a victim of a work accident.', 'Other'),
('64', 'Special agreement', 'An allowance or charge as specified in a special agreement.', 'Other'),
('65', 'Production error discount', 'A discount given for the purchase of a product with a production error.', 'Discount'),
('66', 'New outlet discount', 'A discount given at the occasion of the opening of a new outlet.', 'Discount'),
('67', 'Sample discount', 'A discount given for the purchase of a sample of a product.', 'Discount'),
('68', 'End-of-range discount', 'A discount given for the purchase of an end-of-range product.', 'Discount'),
('69', 'Charge for a customer specific finish', 'A charge for the addition of a customer specific finish to a product.', 'Other Charges'),
('70', 'Incoterm discount', 'A discount given for a specified Incoterm.', 'Discount'),
('71', 'Point of sales threshold allowance', 'Allowance for reaching or exceeding an agreed sales threshold at the point of sales.', 'Other Allowance'),
('72', 'Technical modification costs', 'Costs for technical modifications to a product.', 'Other'),
('73', 'Job-order production costs', 'Costs of job-order production.', 'Other'),
('74', 'Off-premises costs', 'Expenses for non-local activities.', 'Other'),
('75', 'Additional processing costs', 'Costs of additional processing.', 'Other'),
('76', 'Attesting charge', 'Costs of official attestation.', 'Testing/Inspection Charges'),
('77', 'Rush delivery surcharge', 'Charge for increased delivery speed.', 'Other Charges'),
('78', 'Special construction costs', 'Charge for costs incurred as result of special constructions.', 'Other'),
('79', 'Freight charges', 'Amount to be paid for moving goods, by whatever means, from one place to another.', 'Freight Charges'),
('80', 'Packing charge', 'Charge for packing.', 'Packing Charges'),
('81', 'Repair charge', 'Charge for repair.', 'Other Charges'),
('82', 'Loading charge', 'Charge for loading.', 'Loading/Unloading Charges'),
('83', 'Setup charge', 'Charge for setup.', 'Other Charges'),
('84', 'Testing charge', 'Charge for testing.', 'Testing/Inspection Charges'),
('85', 'Warehousing charge', 'Charge for storage and handling.', 'Handling Charges'),
('86', 'Gold surcharge', 'Difference between current price and basic value contained in product price in relation to gold content.', 'Other Charges'),
('87', 'Copper surcharge', 'Difference between current price and basic value contained in product price in relation to copper content.', 'Other Charges'),
('88', 'Material surcharge/deduction', 'Surcharge/deduction, calculated for higher/ lower material''s consumption.', 'Other Charges'),
('89', 'Lead surcharge', 'Difference between current price and basic value contained in product price in relation to lead content.', 'Other Charges'),
('90', 'Price index surcharge', 'Higher/lower price, resulting from change in costs between the times of making offer and delivery.', 'Other Charges'),
('91', 'Platinum surcharge', 'Difference between current price and basic value contained in product price in relation to platinum content.', 'Other Charges'),
('92', 'Silver surcharge', 'Difference between current price and basic value contained in product price in relation to silver content.', 'Other Charges'),
('93', 'Wolfram surcharge', 'Difference between current price and basic value contained in product price in relation to wolfram content.', 'Other Charges'),
('94', 'Aluminum surcharge', 'Difference between current price and basic value contained in product price in relation to aluminum content.', 'Other Charges'),
('95', 'Discount', 'A reduction from a usual or list price.', 'Discount'),
('96', 'Insurance', 'Charge for insurance.', 'Other'),
('97', 'Minimum order / minimum billing charge', 'Charge for minimum order or minimum billing.', 'Other Charges'),
('98', 'Material surcharge (special materials)', 'Surcharge for (special) materials.', 'Other Charges'),
('99', 'Surcharge', 'An additional amount added to the usual charge.', 'Other Charges'),
('100', 'Special rebate', 'A return of part of an amount paid for goods or services, serving as a reduction or discount.', 'Rebate'),
('101', 'Carbon footprint charge', 'A monetary amount charged for carbon footprint related to a regulatory requirement.', 'Other Charges'),
('PP001', 'เงินมัดจำ', '', 'Other'),
('PP002', 'เงินประกัน', '', 'Other'),
('PP003', 'เงินจอง', '', 'Other'),
('PP004', 'เงินจ่ายล่วงหน้า', '', 'Other'),
('PP005', 'เงินประกันผลงาน', '', 'Other'),
('PP006', 'เงินรับล่วงหน้าอื่น ๆ', '', 'Other');

-- End of insert statements
