-- Duty/Tax/Fee Type Code Data Insert Statements
-- Generated from UNECE_DutyTaxFeeTypeCode_D14A.xsd
-- Total records: 53

INSERT INTO duty_tax_fee_type_code (code, name, description, category, is_vat, is_exempt, is_summary) VALUES
('AAA', 'Petroleum tax', 'A tax levied on the volume of petroleum being transacted.', 'Commodity Tax', false, false, false),
('AAB', 'Provisional countervailing duty cash', 'Countervailing duty paid in cash prior to a formal finding of subsidization by Customs.', 'Trade Remedy Duty', false, false, false),
('AAC', 'Provisional countervailing duty bond', 'Countervailing duty paid by posting a bond during an investigation period prior to a formal decision on subsidization by Customs.', 'Trade Remedy Duty', false, false, false),
('AAD', 'Tobacco tax', 'A tax levied on tobacco products.', 'Commodity Tax', false, false, false),
('AAE', 'Energy fee', 'General fee or tax for the use of energy.', 'Environmental Tax', false, false, false),
('AAF', 'Coffee tax', 'A tax levied specifically on coffee products.', 'Commodity Tax', false, false, false),
('AAG', 'Harmonised sales tax, Canadian', 'A harmonized sales tax consisting of a goods and service tax, a Canadian provincial sales tax and, as applicable, a Quebec sales tax which is recoverable.', 'Sales Tax', false, false, false),
('AAH', 'Quebec sales tax', 'A sales tax charged within the Canadian province of Quebec which is recoverable.', 'Sales Tax', false, false, false),
('AAI', 'Canadian provincial sales tax', 'A sales tax charged within Canadian provinces which is non-recoverable.', 'Sales Tax', false, false, false),
('AAJ', 'Tax on replacement part', 'A tax levied on a replacement part, where the original part is returned.', 'Other Tax', false, false, false),
('AAK', 'Mineral oil tax', 'Tax that is levied specifically on products containing mineral oil.', 'Commodity Tax', false, false, false),
('AAL', 'Special tax', 'To indicate a special type of tax.', 'Other Tax', false, false, false),
('ADD', 'Anti-dumping duty', 'Duty applied to goods ruled to have been dumped in an import market at a price lower than that in the exporter''s domestic market.', 'Trade Remedy Duty', false, false, false),
('BOL', 'Stamp duty (Imposta di Bollo)', 'Tax required in Italy, which may be fixed or graduated in various circumstances (e.g. VAT exempt documents or bank receipts).', 'Stamp Duty', false, false, false),
('CAP', 'Agricultural levy', 'Levy imposed on agricultural products where there is a difference between the selling price between trading countries.', 'Agricultural Levy', false, false, false),
('CAR', 'Car tax', 'A tax that is levied on the value of the automobile.', 'Vehicle Tax', false, false, false),
('COC', 'Paper consortium tax (Italy)', 'Italian Paper consortium tax.', 'Other Tax', false, false, false),
('CST', 'Commodity specific tax', 'Tax related to a specified commodity, e.g. illuminants, salts.', 'Other Tax', false, false, false),
('CUD', 'Customs duty', 'Duties laid down in the Customs tariff, to which goods are liable on entering or leaving the Customs territory (CCC).', 'Customs Duty', false, false, false),
('CVD', 'Countervailing duty', 'A duty on imported goods applied for compensate for subsidies granted to those goods in the exporting country.', 'Trade Remedy Duty', false, false, false),
('ENV', 'Environmental tax', 'Tax assessed for funding or assuring environmental protection or clean-up.', 'Environmental Tax', false, false, false),
('EXC', 'Excise duty', 'Customs or fiscal authorities code to identify a specific or ad valorem levy on a specific commodity, applied either domestically or at time of importation.', 'Excise Tax', false, false, false),
('EXP', 'Agricultural export rebate', 'Monetary rebate given to the seller in certain circumstances when agricultural products are exported.', 'Agricultural Levy', false, false, false),
('FET', 'Federal excise tax', 'Tax levied by the federal government on the manufacture of specific items.', 'Excise Tax', false, false, false),
('FRE', 'Free', 'No tax levied.', 'Tax Exempt', false, true, false),
('GCN', 'General construction tax', 'General tax for construction.', 'Construction Tax', false, false, false),
('GST', 'Goods and services tax', 'Tax levied on the final consumption of goods and services throughout the production and distribution chain.', 'GST', false, false, false),
('ILL', 'Illuminants tax', 'Tax of illuminants.', 'Other Tax', false, false, false),
('IMP', 'Import tax', 'Tax assessed on imports.', 'Other Tax', false, false, false),
('IND', 'Individual tax', 'A tax levied based on an individual''s ability to pay.', 'Other Tax', false, false, false),
('LAC', 'Business license fee', 'Government assessed charge for permit to do business.', 'Other Tax', false, false, false),
('LCN', 'Local construction tax', 'Local tax for construction.', 'Construction Tax', false, false, false),
('LDP', 'Light dues payable', 'Fee levied on a vessel to pay for port navigation lights.', 'Other Tax', false, false, false),
('LOC', 'Local sales tax', 'Assessment charges on sale of goods or services by city, borough country or other taxing authorities below state or provincial level.', 'Sales Tax', false, false, false),
('LST', 'Lust tax', 'Tax imposed for clean-up of leaky underground storage tanks.', 'Other Tax', false, false, false),
('MCA', 'Monetary compensatory amount', 'Levy on Common Agricultural Policy (European Union) goods used to compensate for fluctuating currencies between member states.', 'Agricultural Levy', false, false, false),
('MCD', 'Miscellaneous cash deposit', 'Duty paid and held on deposit, by Customs, during an investigation period prior to a final decision being made on any aspect related to imported goods (except valuation) by Customs.', 'Deposit', false, false, false),
('OTH', 'Other taxes', 'Unspecified, miscellaneous tax charges.', 'Other Tax', false, false, false),
('PDB', 'Provisional duty bond', 'Anti-dumping duty paid by posting a bond during an investigation period prior to a formal decision on dumping by Customs.', 'Trade Remedy Duty', false, false, false),
('PDC', 'Provisional duty cash', 'Anti-dumping duty paid in cash prior to a formal finding of dumping by Customs.', 'Trade Remedy Duty', false, false, false),
('PRF', 'Preference duty', 'Duties laid down in the Customs tariff, to which goods are liable on entering or leaving the Customs territory falling under a preferential regime such as Generalised System of Preferences (GSP).', 'Customs Duty', false, false, false),
('SCN', 'Special construction tax', 'Special tax for construction.', 'Construction Tax', false, false, false),
('SSS', 'Shifted social securities', 'Social securities share of the invoice amount to be paid directly to the social securities collector.', 'Other Tax', false, false, false),
('STT', 'State/provincial sales tax', 'All applicable sale taxes by authorities at the state or provincial level, below national level.', 'Sales Tax', false, false, false),
('SUP', 'Suspended duty', 'Duty suspended or deferred from payment.', 'Other Tax', false, false, false),
('SUR', 'Surtax', 'A tax or duty applied on and in addition to existing duties and taxes.', 'Other Tax', false, false, false),
('SWT', 'Shifted wage tax', 'Wage tax share of the invoice amount to be paid directly to the tax collector(s office).', 'Wage Tax', false, false, false),
('TAC', 'Alcohol mark tax', 'A tax levied based on the type of alcohol being obtained.', 'Commodity Tax', false, false, false),
('TOT', 'Total', 'The summary amount of all taxes.', 'Summary', false, false, true),
('TOX', 'Turnover tax', 'Tax levied on the total sales/turnover of a corporation.', 'Turnover Tax', false, false, false),
('TTA', 'Tonnage taxes', 'Tax levied based on the vessel''s net tonnage.', 'Tonnage Tax', false, false, false),
('VAD', 'Valuation deposit', 'Duty paid and held on deposit, by Customs, during an investigation period prior to a formal decision on valuation of the goods being made.', 'Deposit', false, false, false),
('EXE', 'Exempt from tax', 'Goods or services exempt from tax.', 'Tax Exempt', false, true, false),
('TAX', 'Tax', 'General tax code.', 'Other Tax', false, false, false),
('ZZZ', 'Mutually defined', 'A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list.', 'Custom/Other', false, false, false),
('VAT', 'Value added tax', 'A tax on domestic or imported goods applied to the value added at each stage in the production/distribution cycle.', 'VAT', true, false, false);;

-- End of insert statements
