-- ISO Country Code Data Insert Statements
-- Generated from ISO_ISOTwo-letterCountryCode_SecondEdition2006.xsd
-- Total records: 252
-- Standard ISO codes: 249
-- ETDA extensions: 3

-- ETDA Custom Extensions (already inserted in main schema file)
-- INSERT INTO iso_country_code (code, name, description, is_etda_extension, is_active) VALUES
-- ('AN', 'NETHERLANDS ANTILLES*', 'This code is not listed in ISO 3166. ETDA has added for domestic use.', true, false)
-- ('KS', 'KOSOVO*', 'This code is not listed in ISO 3166. ETDA has added for domestic use.', true, true)
-- ('UN', 'UNITED NATIONS*', 'This code is not listed in ISO 3166. ETDA has added for domestic use.', true, true)

-- Standard ISO 3166-1 Country Codes
INSERT INTO iso_country_code (code, name, description, is_etda_extension, is_active) VALUES
('AD', 'ANDORRA', NULL, false, true),
('AE', 'UNITED ARAB EMIRATES', NULL, false, true),
('AF', 'AFGHANISTAN', NULL, false, true),
('AG', 'ANTIGUA AND BARBUDA', NULL, false, true),
('AI', 'ANGUILLA', NULL, false, true),
('AL', 'ALBANIA', NULL, false, true),
('AM', 'ARMENIA', NULL, false, true),
('AO', 'ANGOLA', NULL, false, true),
('AQ', 'ANTARCTICA', NULL, false, true),
('AR', 'ARGENTINA', NULL, false, true),
('AS', 'AMERICAN SAMOA', NULL, false, true),
('AT', 'AUSTRIA', NULL, false, true),
('AU', 'AUSTRALIA', NULL, false, true),
('AW', 'ARUBA', NULL, false, true),
('AX', 'ÅLAND ISLANDS', NULL, false, true),
('AZ', 'AZERBAIJAN', NULL, false, true),
('BA', 'BOSNIA AND HERZEGOVINA', NULL, false, true),
('BB', 'BARBADOS', NULL, false, true),
('BD', 'BANGLADESH', NULL, false, true),
('BE', 'BELGIUM', NULL, false, true),
('BF', 'BURKINA FASO', NULL, false, true),
('BG', 'BULGARIA', NULL, false, true),
('BH', 'BAHRAIN', NULL, false, true),
('BI', 'BURUNDI', NULL, false, true),
('BJ', 'BENIN', NULL, false, true),
('BL', 'SAINT BARTHÉLEMY', NULL, false, true),
('BM', 'BERMUDA', NULL, false, true),
('BN', 'BRUNEI DARUSSALAM', NULL, false, true),
('BO', 'BOLIVIA, PLURINATIONAL STATE OF', NULL, false, true),
('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', NULL, false, true),
('BR', 'BRAZIL', NULL, false, true),
('BS', 'BAHAMAS', NULL, false, true),
('BT', 'BHUTAN', NULL, false, true),
('BV', 'BOUVET ISLAND', NULL, false, true),
('BW', 'BOTSWANA', NULL, false, true),
('BY', 'BELARUS', NULL, false, true),
('BZ', 'BELIZE', NULL, false, true),
('CA', 'CANADA', NULL, false, true),
('CC', 'COCOS (KEELING) ISLANDS', NULL, false, true),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', NULL, false, true),
('CF', 'CENTRAL AFRICAN REPUBLIC', NULL, false, true),
('CG', 'CONGO', NULL, false, true),
('CH', 'SWITZERLAND', NULL, false, true),
('CI', 'COTE D''IVOIRE', NULL, false, true),
('CK', 'COOK ISLANDS', NULL, false, true),
('CL', 'CHILE', NULL, false, true),
('CM', 'CAMEROON', NULL, false, true),
('CN', 'CHINA', NULL, false, true),
('CO', 'COLOMBIA', NULL, false, true),
('CR', 'COSTA RICA', NULL, false, true),
('CU', 'CUBA', NULL, false, true),
('CV', 'CAPE VERDE', NULL, false, true),
('CW', 'CURAÇAO', NULL, false, true),
('CX', 'CHRISTMAS ISLAND', NULL, false, true),
('CY', 'CYPRUS', NULL, false, true),
('CZ', 'CZECH REPUBLIC', NULL, false, true),
('DE', 'GERMANY', NULL, false, true),
('DJ', 'DJIBOUTI', NULL, false, true),
('DK', 'DENMARK', NULL, false, true),
('DM', 'DOMINICA', NULL, false, true),
('DO', 'DOMINICAN REPUBLIC', NULL, false, true),
('DZ', 'ALGERIA', NULL, false, true),
('EC', 'ECUADOR', NULL, false, true),
('EE', 'ESTONIA', NULL, false, true),
('EG', 'EGYPT', NULL, false, true),
('EH', 'WESTERN SAHARA', NULL, false, true),
('ER', 'ERITREA', NULL, false, true),
('ES', 'SPAIN', NULL, false, true),
('ET', 'ETHIOPIA', NULL, false, true),
('FI', 'FINLAND', NULL, false, true),
('FJ', 'FIJI', NULL, false, true),
('FK', 'FALKLAND ISLANDS (MALVINAS)', NULL, false, true),
('FM', 'MICRONESIA, FEDERATED STATES OF', NULL, false, true),
('FO', 'FAROE ISLANDS', NULL, false, true),
('FR', 'FRANCE', NULL, false, true),
('GA', 'GABON', NULL, false, true),
('GB', 'UNITED KINGDOM', NULL, false, true),
('GD', 'GRENADA', NULL, false, true),
('GE', 'GEORGIA', NULL, false, true),
('GF', 'FRENCH GUIANA', NULL, false, true),
('GG', 'GUERNSEY', NULL, false, true),
('GH', 'GHANA', NULL, false, true),
('GI', 'GIBRALTAR', NULL, false, true),
('GL', 'GREENLAND', NULL, false, true),
('GM', 'GAMBIA', NULL, false, true),
('GN', 'GUINEA', NULL, false, true),
('GP', 'GUADELOUPE', NULL, false, true),
('GQ', 'EQUATORIAL GUINEA', NULL, false, true),
('GR', 'GREECE', NULL, false, true),
('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', NULL, false, true),
('GT', 'GUATEMALA', NULL, false, true),
('GU', 'GUAM', NULL, false, true),
('GW', 'GUINEA-BISSAU', NULL, false, true),
('GY', 'GUYANA', NULL, false, true),
('HK', 'HONG KONG', NULL, false, true),
('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', NULL, false, true),
('HN', 'HONDURAS', NULL, false, true),
('HR', 'CROATIA', NULL, false, true),
('HT', 'HAITI', NULL, false, true),
('HU', 'HUNGARY', NULL, false, true),
('ID', 'INDONESIA', NULL, false, true),
('IE', 'IRELAND', NULL, false, true),
('IL', 'ISRAEL', NULL, false, true),
('IM', 'ISLE OF MAN', NULL, false, true),
('IN', 'INDIA', NULL, false, true),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', NULL, false, true),
('IQ', 'IRAQ', NULL, false, true),
('IR', 'IRAN, ISLAMIC REPUBLIC OF', NULL, false, true),
('IS', 'ICELAND', NULL, false, true),
('IT', 'ITALY', NULL, false, true),
('JE', 'JERSEY', NULL, false, true),
('JM', 'JAMAICA', NULL, false, true),
('JO', 'JORDAN', NULL, false, true),
('JP', 'JAPAN', NULL, false, true),
('KE', 'KENYA', NULL, false, true),
('KG', 'KYRGYZSTAN', NULL, false, true),
('KH', 'CAMBODIA', NULL, false, true),
('KI', 'KIRIBATI', NULL, false, true),
('KM', 'COMOROS', NULL, false, true),
('KN', 'SAINT KITTS AND NEVIS', NULL, false, true),
('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', NULL, false, true),
('KR', 'KOREA, REPUBLIC OF', NULL, false, true),
('KW', 'KUWAIT', NULL, false, true),
('KY', 'CAYMAN ISLANDS', NULL, false, true),
('KZ', 'KAZAKHSTAN', NULL, false, true),
('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', NULL, false, true),
('LB', 'LEBANON', NULL, false, true),
('LC', 'SAINT LUCIA', NULL, false, true),
('LI', 'LIECHTENSTEIN', NULL, false, true),
('LK', 'SRI LANKA', NULL, false, true),
('LR', 'LIBERIA', NULL, false, true),
('LS', 'LESOTHO', NULL, false, true),
('LT', 'LITHUANIA', NULL, false, true),
('LU', 'LUXEMBOURG', NULL, false, true),
('LV', 'LATVIA', NULL, false, true),
('LY', 'LIBYA', NULL, false, true),
('MA', 'MOROCCO', NULL, false, true),
('MC', 'MONACO', NULL, false, true),
('MD', 'MOLDOVA', NULL, false, true),
('ME', 'MONTENEGRO', NULL, false, true),
('MF', 'SAINT MARTIN (FRENCH PART)', NULL, false, true),
('MG', 'MADAGASCAR', NULL, false, true),
('MH', 'MARSHALL ISLANDS', NULL, false, true),
('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', NULL, false, true),
('ML', 'MALI', NULL, false, true),
('MM', 'MYANMAR', NULL, false, true),
('MN', 'MONGOLIA', NULL, false, true),
('MO', 'MACAO', NULL, false, true),
('MP', 'NORTHERN MARIANA ISLANDS', NULL, false, true),
('MQ', 'MARTINIQUE', NULL, false, true),
('MR', 'MAURITANIA', NULL, false, true),
('MS', 'MONTSERRAT', NULL, false, true),
('MT', 'MALTA', NULL, false, true),
('MU', 'MAURITIUS', NULL, false, true),
('MV', 'MALDIVES', NULL, false, true),
('MW', 'MALAWI', NULL, false, true),
('MX', 'MEXICO', NULL, false, true),
('MY', 'MALAYSIA', NULL, false, true),
('MZ', 'MOZAMBIQUE', NULL, false, true),
('NA', 'NAMIBIA', NULL, false, true),
('NC', 'NEW CALEDONIA', NULL, false, true),
('NE', 'NIGER', NULL, false, true),
('NF', 'NORFOLK ISLAND', NULL, false, true),
('NG', 'NIGERIA', NULL, false, true),
('NI', 'NICARAGUA', NULL, false, true),
('NL', 'NETHERLANDS', NULL, false, true),
('NO', 'NORWAY', NULL, false, true),
('NP', 'NEPAL', NULL, false, true),
('NR', 'NAURU', NULL, false, true),
('NU', 'NIUE', NULL, false, true),
('NZ', 'NEW ZEALAND', NULL, false, true),
('OM', 'OMAN', NULL, false, true),
('PA', 'PANAMA', NULL, false, true),
('PE', 'PERU', NULL, false, true),
('PF', 'FRENCH POLYNESIA', NULL, false, true),
('PG', 'PAPUA NEW GUINEA', NULL, false, true),
('PH', 'PHILIPPINES', NULL, false, true),
('PK', 'PAKISTAN', NULL, false, true),
('PL', 'POLAND', NULL, false, true),
('PM', 'SAINT PIERRE AND MIQUELON', NULL, false, true),
('PN', 'PITCAIRN', NULL, false, true),
('PR', 'PUERTO RICO', NULL, false, true),
('PS', 'PALESTINE, STATE OF', NULL, false, true),
('PT', 'PORTUGAL', NULL, false, true),
('PW', 'PALAU', NULL, false, true),
('PY', 'PARAGUAY', NULL, false, true),
('QA', 'QATAR', NULL, false, true),
('RE', 'REUNION', NULL, false, true),
('RO', 'ROMANIA', NULL, false, true),
('RS', 'SERBIA', NULL, false, true),
('RU', 'RUSSIAN FEDERATION', NULL, false, true),
('RW', 'RWANDA', NULL, false, true),
('SA', 'SAUDI ARABIA', NULL, false, true),
('SB', 'SOLOMON ISLANDS', NULL, false, true),
('SC', 'SEYCHELLES', NULL, false, true),
('SD', 'SUDAN', NULL, false, true),
('SE', 'SWEDEN', NULL, false, true),
('SG', 'SINGAPORE', NULL, false, true),
('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', NULL, false, true),
('SI', 'SLOVENIA', NULL, false, true),
('SJ', 'SVALBARD AND JAN MAYEN', NULL, false, true),
('SK', 'SLOVAKIA', NULL, false, true),
('SL', 'SIERRA LEONE', NULL, false, true),
('SM', 'SAN MARINO', NULL, false, true),
('SN', 'SENEGAL', NULL, false, true),
('SO', 'SOMALIA', NULL, false, true),
('SR', 'SURINAME', NULL, false, true),
('SS', 'SOUTH SUDAN', NULL, false, true),
('ST', 'SAO TOME AND PRINCIPE', NULL, false, true),
('SV', 'EL SALVADOR', NULL, false, true),
('SX', 'SINT MAARTEN (DUTCH PART)', NULL, false, true),
('SY', 'SYRIAN ARAB REPUBLIC', NULL, false, true),
('SZ', 'SWAZILAND', NULL, false, true),
('TC', 'TURKS AND CAICOS ISLANDS', NULL, false, true),
('TD', 'CHAD', NULL, false, true),
('TF', 'FRENCH SOUTHERN TERRITORIES', NULL, false, true),
('TG', 'TOGO', NULL, false, true),
('TH', 'THAILAND', NULL, false, true),
('TJ', 'TAJIKISTAN', NULL, false, true),
('TK', 'TOKELAU', NULL, false, true),
('TL', 'TIMOR-LESTE', NULL, false, true),
('TM', 'TURKMENISTAN', NULL, false, true),
('TN', 'TUNISIA', NULL, false, true),
('TO', 'TONGA', NULL, false, true),
('TR', 'TURKEY', NULL, false, true),
('TT', 'TRINIDAD AND TOBAGO', NULL, false, true),
('TV', 'TUVALU', NULL, false, true),
('TW', 'TAIWAN, PROVINCE OF CHINA', NULL, false, true),
('TZ', 'TANZANIA, UNITED REPUBLIC OF', NULL, false, true),
('UA', 'UKRAINE', NULL, false, true),
('UG', 'UGANDA', NULL, false, true),
('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', NULL, false, true),
('US', 'UNITED STATES', NULL, false, true),
('UY', 'URUGUAY', NULL, false, true),
('UZ', 'UZBEKISTAN', NULL, false, true),
('VA', 'HOLY SEE (VATICAN CITY STATE)', NULL, false, true),
('VC', 'SAINT VINCENT AND THE GRENADINES', NULL, false, true),
('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', NULL, false, true),
('VG', 'VIRGIN ISLANDS, BRITISH', NULL, false, true),
('VI', 'VIRGIN ISLANDS, U.S.', NULL, false, true),
('VN', 'VIET NAM', NULL, false, true),
('VU', 'VANUATU', NULL, false, true),
('WF', 'WALLIS AND FUTUNA', NULL, false, true),
('WS', 'SAMOA', NULL, false, true),
('YE', 'YEMEN', NULL, false, true),
('YT', 'MAYOTTE', NULL, false, true),
('ZA', 'SOUTH AFRICA', NULL, false, true),
('ZM', 'ZAMBIA', NULL, false, true),
('ZW', 'ZIMBABWE', NULL, false, true);;

-- End of insert statements
