-- ISO Currency Code Data Insert Statements
-- Generated from ISO_ISO3AlphaCurrencyCode_2012-08-31.xsd
-- Total records: 172

INSERT INTO iso_currency_code (code, name, description, numeric_code, minor_units, is_active) VALUES
('AED', 'Dirham', NULL, '784', 2, true),
('AFN', 'Afghani', NULL, '971', 2, true),
('ALL', 'Lek', NULL, '008', 2, true),
('AMD', 'Dram', NULL, '051', 2, true),
('ANG', 'Netherlands Antillian Guilder', NULL, '532', 2, true),
('AOA', 'Kwanza', NULL, '973', 2, true),
('ARS', 'Argentine Peso', NULL, '032', 2, true),
('AUD', 'Australian Dollar', NULL, '036', 2, true),
('AWG', 'Aruban Florin', NULL, '533', 2, true),
('AZN', 'Azerbaijanian Manat', NULL, '944', 2, true),
('BAM', 'Convertible Mark', NULL, '977', 2, true),
('BBD', 'Barbados Dollar', NULL, '052', 2, true),
('BDT', 'Taka', NULL, '050', 2, true),
('BGN', 'Bulgarian Lev', NULL, '975', 2, true),
('BHD', 'Bahraini Dinar', NULL, '048', 3, true),
('BIF', 'Burundi Franc', NULL, '108', 0, true),
('BMD', 'Bermudian Dollar (customarily: Bermuda Dollar)', NULL, '060', 2, true),
('BND', 'Brunei Dollar', NULL, '096', 2, true),
('BOB', 'Boliviano', NULL, '068', 2, true),
('BRL', 'Brazilian Real', NULL, '986', 2, true),
('BSD', 'Bahamian Dollar', NULL, '044', 2, true),
('BTN', 'Ngultrum', NULL, '064', 2, true),
('BWP', 'Pula', NULL, '072', 2, true),
('BYR', 'Belarussian Ruble', NULL, '974', 0, true),
('BZD', 'Belize Dollar', NULL, '084', 2, true),
('CAD', 'Canadian Dollar', NULL, '124', 2, true),
('CDF', 'Franc Congolais', NULL, '976', 2, true),
('CHE', 'WIR Euro', NULL, NULL, 2, true),
('CHF', 'Swiss Franc', NULL, '756', 2, true),
('CHW', 'WIR Franc', NULL, NULL, 2, true),
('CLP', 'Chilean Peso', NULL, '152', 0, true),
('CNY', 'Yuan Renminbi', NULL, '156', 2, true),
('COP', 'Colombian Peso', NULL, '170', 2, true),
('COU', 'Unidad de Valor Real', NULL, NULL, 2, true),
('CRC', 'Costa Rican Colon', NULL, '188', 2, true),
('CUC', 'Peso Convertible', NULL, '931', 2, true),
('CUP', 'Cuban Peso', NULL, '192', 2, true),
('CVE', 'Cape Verde Escudo', NULL, '132', 2, true),
('CZK', 'Czech Koruna', NULL, '203', 2, true),
('DJF', 'Djibouti Franc', NULL, '262', 0, true),
('DKK', 'Danish Krone', NULL, '208', 2, true),
('DOP', 'Dominican Peso', NULL, '214', 2, true),
('DZD', 'Algerian Dinar', NULL, '012', 2, true),
('EEK', 'Kroon', NULL, NULL, 2, true),
('EGP', 'Egyptian Pound', NULL, '818', 2, true),
('ERN', 'Nakfa', NULL, '232', 2, true),
('ETB', 'Ethopian Birr', NULL, '230', 2, true),
('EUR', 'Euro', NULL, '978', 2, true),
('FJD', 'Fiji Dollar', NULL, '242', 2, true),
('FKP', 'Falkland Islands Pound', NULL, '238', 2, true),
('GBP', 'Pound Sterling', NULL, '826', 2, true),
('GEL', 'Lari', NULL, '981', 2, true),
('GHS', 'Ghana Cedi', NULL, '936', 2, true),
('GIP', 'Gibraltar Pound', NULL, '292', 2, true),
('GMD', 'Dalasi', NULL, '270', 2, true),
('GNF', 'Guinea Franc', NULL, '324', 0, true),
('GTQ', 'Quetzal', NULL, '320', 2, true),
('GYD', 'Guyana Dollar', NULL, '328', 2, true),
('HKD', 'Honk Kong Dollar', NULL, '344', 2, true),
('HNL', 'Lempira', NULL, '340', 2, true),
('HRK', 'Kuna', NULL, '191', 2, true),
('HTG', 'Gourde', NULL, '332', 2, true),
('HUF', 'Forint', NULL, '348', 2, true),
('IDR', 'Rupiah', NULL, '360', 2, true),
('ILS', 'New Israeli Sheqel', NULL, '376', 2, true),
('INR', 'Indian Rupee', NULL, '356', 2, true),
('IQD', 'Iraqi Dinar', NULL, '368', 3, true),
('IRR', 'Iranian Rial', NULL, '364', 2, true),
('ISK', 'Iceland Krona', NULL, '352', 0, true),
('JMD', 'Jamaican Dollar', NULL, '388', 2, true),
('JOD', 'Jordanian Dinar', NULL, '400', 3, true),
('JPY', 'Yen', NULL, '392', 0, true),
('KES', 'Kenyan Shilling', NULL, '404', 2, true),
('KGS', 'Som', NULL, '417', 2, true),
('KHR', 'Riel', NULL, '116', 2, true),
('KMF', 'Comoro Franc', NULL, '174', 0, true),
('KPW', 'North Korean Won', NULL, '408', 2, true),
('KRW', 'Won', NULL, '410', 0, true),
('KWD', 'Kuwaiti Dinar', NULL, '414', 3, true),
('KYD', 'Cayman Islands Dollar', NULL, '136', 2, true),
('KZT', 'Tenge', NULL, '398', 2, true),
('LAK', 'Kip', NULL, '418', 2, true),
('LBP', 'Lebanese Pound', NULL, '422', 2, true),
('LKR', 'Sri Lanka Rupee', NULL, '144', 2, true),
('LRD', 'Liberian Dollar', NULL, '430', 2, true),
('LSL', 'Loti', NULL, '426', 2, true),
('LTL', 'Lithuanian Litas', NULL, NULL, 2, true),
('LVL', 'Latvian Lats', NULL, NULL, 2, true),
('LYD', 'Libyan Dinar', NULL, '434', 3, true),
('MAD', 'Morrocan Dirham', NULL, '504', 2, true),
('MDL', 'Moldovan Leu', NULL, '498', 2, true),
('MGA', 'Ariary', NULL, '969', 2, true),
('MKD', 'Denar', NULL, '807', 2, true),
('MMK', 'Kyat', NULL, '104', 2, true),
('MNT', 'Tugrik', NULL, '496', 2, true),
('MOP', 'Pataca', NULL, '446', 2, true),
('MRO', 'Ouguiya', NULL, '478', 2, true),
('MUR', 'Mauritius Rupee', NULL, '480', 2, true),
('MVR', 'Rufiyaa', NULL, '462', 2, true),
('MWK', 'Kwacha', NULL, '454', 2, true),
('MXN', 'Mexican Peso', NULL, '484', 2, true),
('MYR', 'Malaysian Ringgit', NULL, '458', 2, true),
('MZM', 'Mozambique Metical', NULL, NULL, 2, true),
('NAD', 'Namibia Dollar', NULL, '516', 2, true),
('NGN', 'Naira', NULL, '566', 2, true),
('NIO', 'Cordoba Oro', NULL, '558', 2, true),
('NOK', 'Norwegian Krone', NULL, '578', 2, true),
('NPR', 'Nepalese Rupee', NULL, '524', 2, true),
('NZD', 'New Zealand Dollar', NULL, '554', 2, true),
('OMR', 'Rial Omani', NULL, '512', 3, true),
('PAB', 'Balboa', NULL, '590', 2, true),
('PEN', 'Nuevo Sol', NULL, '604', 2, true),
('PGK', 'Kina', NULL, '598', 2, true),
('PHP', 'Philippine Peso', NULL, '608', 2, true),
('PKR', 'Pakistan Rupee', NULL, '586', 2, true),
('PLN', 'Zloty', NULL, '985', 2, true),
('PYG', 'Guarani', NULL, '600', 0, true),
('QAR', 'Qatari Rial', NULL, '634', 2, true),
('ROL', 'old Romanian Leu', 'This currency code is valid until 30 June 2005, but the currency itself will remain legal until 31 December 2006 when it will be withdrawn.', NULL, 2, true),
('RON', 'new Romanian Leu', 'This currency code is effective from 1 July 2005', '946', 2, true),
('RSD', 'Serbian Dinar', NULL, '941', 2, true),
('RUB', 'Russian Ruble', NULL, '643', 2, true),
('RWF', 'Rwanda Franc', NULL, '646', 0, true),
('SAR', 'Saudi Riyal', NULL, '682', 2, true),
('SBD', 'Solomon Islands Dollar', NULL, '090', 2, true),
('SCR', 'Seychelles Rupee', NULL, '690', 2, true),
('SDG', 'Sudanese Pound', NULL, '938', 2, true),
('SEK', 'Swedish Krona', NULL, '752', 2, true),
('SGD', 'Singapore Dollar', NULL, '702', 2, true),
('SHP', 'St. Helena Pound', NULL, '654', 2, true),
('SLL', 'Leone', NULL, '694', 2, true),
('SOS', 'Somali Shilling', NULL, '706', 2, true),
('SRD', 'Suriname Dollar', NULL, '968', 2, true),
('SSP', 'South Sudanese Pound', NULL, '728', 2, true),
('STD', 'Dobra', NULL, '678', 2, true),
('SVC', 'El Salvador Colon', NULL, NULL, 2, true),
('SYP', 'Syrian Pound', NULL, '760', 2, true),
('SZL', 'Lilangeni', NULL, '748', 2, true),
('THB', 'Baht', NULL, '764', 2, true),
('TJS', 'Somoni', NULL, '972', 2, true),
('TMT', 'Turkmenistan New Manat', NULL, '934', 2, true),
('TND', 'Tunisian Dinar', NULL, '788', 3, true),
('TOP', 'Pa''anga', NULL, '776', 2, true),
('TRY', 'Turkish Lira', NULL, '949', 2, true),
('TTD', 'Trinidad and Tobago Dollar', NULL, '780', 2, true),
('TWD', 'New Taiwan Dollar', NULL, '901', 2, true),
('TZS', 'Tanzanian Shilling', NULL, '834', 2, true),
('UAH', 'Hryvnia', NULL, '980', 2, true),
('UGX', 'Uganda Shilling', NULL, '800', 0, true),
('USD', 'US Dollar', NULL, '840', 2, true),
('UYI', 'Uruguayo Peso en Unidades Indexadas', NULL, NULL, 2, true),
('UYU', 'Peso Uruguayo', NULL, '858', 2, true),
('UZS', 'Uzbekistan Sum', NULL, '860', 2, true),
('VEF', 'Bolivar', NULL, '937', 2, true),
('VND', 'Dong', NULL, '704', 0, true),
('VUV', 'Vatu', NULL, '548', 0, true),
('WST', 'Tala', NULL, '882', 2, true),
('XAF', 'CFA Franc', NULL, '950', 0, true),
('XAG', 'Silver', NULL, NULL, 2, true),
('XAU', 'Gold', NULL, NULL, 2, true),
('XCD', 'East Carribean Dollar', NULL, '951', 2, true),
('XDR', 'SDR', NULL, NULL, 2, true),
('XOF', 'CFA Franc', NULL, '952', 0, true),
('XPD', 'Palladium', NULL, NULL, 2, true),
('XPF', 'CFP Franc', NULL, '953', 0, true),
('XPT', 'Platinum', NULL, NULL, 2, true),
('XSU', 'Sucre', NULL, NULL, 2, true),
('XUA', 'ADB Unit of Account', NULL, NULL, 2, true),
('YER', 'Yemeni Rial', NULL, '886', 2, true),
('ZAR', 'Rand', NULL, '710', 2, true),
('ZMW', 'Zambian Kwacha', NULL, '967', 2, true),
('ZWL', 'Zimbabwe Dollar', '(effective 1 February 2009)', '932', 2, true);;

-- End of insert statements
