-- ISO Language Code Data Insert Statements
-- Generated from ISO_ISO2AlphaLanguageCode_2006-10-27.xsd
-- Total unique languages: 185
-- Note: Deduplicated from XSD which contains both lowercase and uppercase variants

INSERT INTO iso_language_code (code, name, is_active) VALUES
('aa', 'Afar', true),
('ab', 'Abkhazian', true),
('ae', 'Avestan', true),
('af', 'Afrikaans', true),
('ak', 'Akan', true),
('am', 'Amharic', true),
('an', 'Aragonese', true),
('ar', 'Arabic', true),
('as', 'Assamese', true),
('av', 'Avaric', true),
('ay', 'Aymara', true),
('az', 'Azerbaijani', true),
('ba', 'Bashkir', true),
('be', 'Belarusian', true),
('bg', 'Bulgarian', true),
('bh', 'Bihari languages', true),
('bi', 'Bislama', true),
('bm', 'Bambara', true),
('bn', 'Bengali', true),
('bo', 'Tibetan', true),
('br', 'Breton', true),
('bs', 'Bosnian', true),
('ca', 'Catalan; Valencian', true),
('ce', 'Chechen', true),
('ch', 'Chamorro', true),
('co', 'Corsican', true),
('cr', 'Cree', true),
('cs', 'Czech', true),
('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', true),
('cv', 'Chuvash', true),
('cy', 'Welsh', true),
('da', 'Danish', true),
('de', 'German', true),
('dv', 'Divehi; Dhivehi; Maldivian', true),
('dz', 'Dzongkha', true),
('ee', 'Ewe', true),
('el', 'Greek; Modern (1453-)', true),
('en', 'English', true),
('eo', 'Esperanto', true),
('es', 'Spanish; Castilian', true),
('et', 'Estonian', true),
('eu', 'Basque', true),
('fa', 'Persian', true),
('ff', 'Fulah', true),
('fi', 'Finnish', true),
('fj', 'Fijian', true),
('fo', 'Faroese', true),
('fr', 'French', true),
('fy', 'Western Frisian', true),
('ga', 'Irish', true),
('gd', 'Gaelic; Scottish Gaelic', true),
('gl', 'Galician', true),
('gn', 'Guarani', true),
('gu', 'Gujarati', true),
('gv', 'Manx', true),
('ha', 'Hausa', true),
('he', 'Hebrew', true),
('hi', 'Hindi', true),
('ho', 'Hiri Motu', true),
('hr', 'Croatian', true),
('ht', 'Haitian; Haitian Creole', true),
('hu', 'Hungarian', true),
('hy', 'Armenian', true),
('hz', 'Herero', true),
('ia', 'Interlingua (International Auxiliary Language Association)', true),
('id', 'Indonesian', true),
('ie', 'Interlingue; Occidental', true),
('ig', 'Igbo', true),
('ii', 'Sichuan Yi; Nuosu', true),
('ik', 'Inupiaq', true),
('io', 'Ido', true),
('is', 'Icelandic', true),
('it', 'Italian', true),
('iu', 'Inuktiut', true),
('ja', 'Japanese', true),
('jv', 'Javanese', true),
('ka', 'Georgian', true),
('kg', 'Kongo', true),
('ki', 'Kikuyu; Gikuyu', true),
('kj', 'Kuanyama; Kwanyama', true),
('kk', 'Kazakh', true),
('kl', 'Kalaallisut; Greenlandic', true),
('km', 'Central Khmer', true),
('kn', 'Kannada', true),
('ko', 'Korean', true),
('kr', 'Kanuri', true),
('ks', 'Kashmiri', true),
('ku', 'Kurdish', true),
('kv', 'Komi', true),
('kw', 'Cornish', true),
('ky', 'Kirghiz; Kyrgyz', true),
('la', 'Latin', true),
('lb', 'Luxembourgish; Letzeburgesch', true),
('lg', 'Ganda', true),
('li', 'Limburgan; Limburger; Limburgish', true),
('ln', 'Lingala', true),
('lo', 'Lao', true),
('lt', 'Lithuanian', true),
('lu', 'Luba-Katanga', true),
('lv', 'Latvian', true),
('mg', 'Malagasy', true),
('mh', 'Marshallese', true),
('mi', 'Maori', true),
('mk', 'Macedonian', true),
('ml', 'Malayalam', true),
('mn', 'Mongolian', true),
('mo', 'Moldavian; Moldovan', true),
('mr', 'Marathi', true),
('ms', 'Malay', true),
('mt', 'Maltese', true),
('my', 'Burmese', true),
('na', 'Nauru', true),
('nb', 'Bokmal Norwegian; Norwegian Bokmal', true),
('nd', 'Ndebele; North; North Ndebele', true),
('ne', 'Nepali', true),
('ng', 'Ndonga', true),
('nl', 'Dutch; Flemish', true),
('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian', true),
('no', 'Norwegian', true),
('nr', 'Ndebele; South; South Ndebele', true),
('nv', 'Navajo; Navaho', true),
('ny', 'Chichewa; Chewa; Nyanja', true),
('oc', 'Occitan (post 1500)', true),
('oj', 'Ojibwa', true),
('om', 'Oromo', true),
('or', 'Oriya', true),
('os', 'Ossetian; Ossetic', true),
('pa', 'Panjabi; Punjabi', true),
('pi', 'Pali', true),
('pl', 'Polish', true),
('ps', 'Pushto; Pashto', true),
('pt', 'Portuguese', true),
('qu', 'Quechua', true),
('rm', 'Romansh', true),
('rn', 'Rundi', true),
('ro', 'Romanian', true),
('ru', 'Russian', true),
('rw', 'Kinyarwanda', true),
('sa', 'Sanskrit', true),
('sc', 'Sardinian', true),
('sd', 'Sindhi', true),
('se', 'Northern Sami', true),
('sg', 'Sango', true),
('si', 'Sinhala; Sinhalese', true),
('sk', 'Slovak', true),
('sl', 'Slovenian', true),
('sm', 'Samoan', true),
('sn', 'Shona', true),
('so', 'Somali', true),
('sq', 'Albanian', true),
('sr', 'Serbian', true),
('ss', 'Swati', true),
('st', 'Sotho, Southern', true),
('su', 'Sundanese', true),
('sv', 'Swedish', true),
('sw', 'Swahili', true),
('ta', 'Tamil', true),
('te', 'Telugu', true),
('tg', 'Tajik', true),
('th', 'Thai', true),
('ti', 'Tigrinya', true),
('tk', 'Turkmen', true),
('tl', 'Tagalog', true),
('tn', 'Tswana', true),
('to', 'Tonga (Tonga Islands)', true),
('tr', 'Turkish', true),
('ts', 'Tsonga', true),
('tt', 'Tatar', true),
('tw', 'Twi', true),
('ty', 'Tahitian', true),
('ug', 'Uighur; Uyghur', true),
('uk', 'Ukrainian', true),
('ur', 'Urdu', true),
('uz', 'Uzbek', true),
('ve', 'Venda', true),
('vi', 'Vietnamese', true),
('vo', 'Volapük', true),
('wa', 'Walloon', true),
('wo', 'Wolof', true),
('xh', 'Xhosa', true),
('yi', 'Yiddish', true),
('yo', 'Yoruba', true),
('za', 'Zhuang; Chuang', true),
('zh', 'Chinese', true),
('zu', 'Zulu', true);

-- End of insert statements
