-- ISO Language Code Data Insert Statements
-- Generated from ISO_ISO2AlphaLanguageCode_2006-10-27.xsd
-- Total language code entries: 370
-- Includes both lowercase and uppercase variants as defined in the XSD schema

INSERT INTO iso_language_code (code, name, is_active) VALUES
('aa', 'Afar', true),
('AA', 'Afar', true),
('ab', 'Abkhazian', true),
('AB', 'Abkhazian', true),
('ae', 'Avestan', true),
('AE', 'Avestan', true),
('af', 'Afrikaans', true),
('AF', 'Afrikaans', true),
('ak', 'Akan', true),
('AK', 'Akan', true),
('am', 'Amharic', true),
('AM', 'Amharic', true),
('an', 'Aragonese', true),
('AN', 'Aragonese', true),
('ar', 'Arabic', true),
('AR', 'Arabic', true),
('as', 'Assamese', true),
('AS', 'Assamese', true),
('av', 'Avaric', true),
('AV', 'Avaric', true),
('ay', 'Aymara', true),
('AY', 'Aymara', true),
('az', 'Azerbaijani', true),
('AZ', 'Azerbaijani', true),
('ba', 'Bashkir', true),
('BA', 'Bashkir', true),
('be', 'Belarusian', true),
('BE', 'Belarusian', true),
('bg', 'Bulgarian', true),
('BG', 'Bulgarian', true),
('bh', 'Bihari languages', true),
('BH', 'Bihari languages', true),
('bi', 'Bislama', true),
('BI', 'Bislama', true),
('bm', 'Bambara', true),
('BM', 'Bambara', true),
('bn', 'Bengali', true),
('BN', 'Bengali', true),
('bo', 'Tibetan', true),
('BO', 'Tibetan', true),
('br', 'Breton', true),
('BR', 'Breton', true),
('bs', 'Bosnian', true),
('BS', 'Bosnian', true),
('ca', 'Catalan; Valencian', true),
('CA', 'Catalan; Valencian', true),
('ce', 'Chechen', true),
('CE', 'Chechen', true),
('ch', 'Chamorro', true),
('CH', 'Chamorro', true),
('co', 'Corsican', true),
('CO', 'Corsican', true),
('cr', 'Cree', true),
('CR', 'Cree', true),
('cs', 'Czech', true),
('CS', 'Czech', true),
('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', true),
('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', true),
('cv', 'Chuvash', true),
('CV', 'Chuvash', true),
('cy', 'Welsh', true),
('CY', 'Welsh', true),
('da', 'Danish', true),
('DA', 'Danish', true),
('de', 'German', true),
('DE', 'German', true),
('dv', 'Divehi; Dhivehi; Maldivian', true),
('DV', 'Divehi; Dhivehi; Maldivian', true),
('dz', 'Dzongkha', true),
('DZ', 'Dzongkha', true),
('ee', 'Ewe', true),
('EE', 'Ewe', true),
('el', 'Greek, Modern (1453-)', true),
('EL', 'Greek, Modern (1453-)', true),
('en', 'English', true),
('EN', 'English', true),
('eo', 'Esperanto', true),
('EO', 'Esperanto', true),
('es', 'Spanish; Castilian', true),
('ES', 'Spanish; Castilian', true),
('et', 'Estonian', true),
('ET', 'Estonian', true),
('eu', 'Basque', true),
('EU', 'Basque', true),
('fa', 'Persian', true),
('FA', 'Persian', true),
('ff', 'Fulah', true),
('FF', 'Fulah', true),
('fi', 'Finnish', true),
('FI', 'Finnish', true),
('fj', 'Fijian', true),
('FJ', 'Fijian', true),
('fo', 'Faroese', true),
('FO', 'Faroese', true),
('fr', 'French', true),
('FR', 'French', true),
('fy', 'Western Frisian', true),
('FY', 'Western Frisian', true),
('ga', 'Irish', true),
('GA', 'Irish', true),
('gd', 'Gaelic; Scottish Gaelic', true),
('GD', 'Gaelic; Scottish Gaelic', true),
('gl', 'Galician', true),
('GL', 'Galician', true),
('gn', 'Guarani', true),
('GN', 'Guarani', true),
('gu', 'Gujarati', true),
('GU', 'Gujarati', true),
('gv', 'Manx', true),
('GV', 'Manx', true),
('ha', 'Hausa', true),
('HA', 'Hausa', true),
('he', 'Hebrew', true),
('HE', 'Hebrew', true),
('hi', 'Hindi', true),
('HI', 'Hindi', true),
('ho', 'Hiri Motu', true),
('HO', 'Hiri Motu', true),
('hr', 'Croatian', true),
('HR', 'Croatian', true),
('ht', 'Haitian; Haitian Creole', true),
('HT', 'Haitian; Haitian Creole', true),
('hu', 'Hungarian', true),
('HU', 'Hungarian', true),
('hy', 'Armenian', true),
('HY', 'Armenian', true),
('hz', 'Herero', true),
('HZ', 'Herero', true),
('ia', 'Interlingua (International Auxiliary Language Association)', true),
('IA', 'Interlingua (International Auxiliary Language Association)', true),
('id', 'Indonesian', true),
('ID', 'Indonesian', true),
('ie', 'Interlingue; Occidental', true),
('IE', 'Interlingue; Occidental', true),
('ig', 'Igbo', true),
('IG', 'Igbo', true),
('ii', 'Sichuan Yi; Nuosu', true),
('II', 'Sichuan Yi; Nuosu', true),
('ik', 'Inupiaq', true),
('IK', 'Inupiaq', true),
('io', 'Ido', true),
('IO', 'Ido', true),
('is', 'Icelandic', true),
('IS', 'Icelandic', true),
('it', 'Italian', true),
('IT', 'Italian', true),
('iu', 'Inuktitut', true),
('IU', 'Inuktitut', true),
('ja', 'Japanese', true),
('JA', 'Japanese', true),
('jv', 'Javanese', true),
('JV', 'Javanese', true),
('ka', 'Georgian', true),
('KA', 'Georgian', true),
('kg', 'Kongo', true),
('KG', 'Kongo', true),
('ki', 'Kikuyu; Gikuyu', true),
('KI', 'Kikuyu; Gikuyu', true),
('kj', 'Kuanyama; Kwanyama', true),
('KJ', 'Kuanyama; Kwanyama', true),
('kk', 'Kazakh', true),
('KK', 'Kazakh', true),
('kl', 'Kalaallisut; Greenlandic', true),
('KL', 'Kalaallisut; Greenlandic', true),
('km', 'Central Khmer', true),
('KM', 'Central Khmer', true),
('kn', 'Kannada', true),
('KN', 'Kannada', true),
('ko', 'Korean', true),
('KO', 'Korean', true),
('kr', 'Kanuri', true),
('KR', 'Kanuri', true),
('ks', 'Kashmiri', true),
('KS', 'Kashmiri', true),
('ku', 'Kurdish', true),
('KU', 'Kurdish', true),
('kv', 'Komi', true),
('KV', 'Komi', true),
('kw', 'Cornish', true),
('KW', 'Cornish', true),
('ky', 'Kirghiz; Kyrgyz', true),
('KY', 'Kirghiz; Kyrgyz', true),
('la', 'Latin', true),
('LA', 'Latin', true),
('lb', 'Luxembourgish; Letzeburgesch', true),
('LB', 'Luxembourgish; Letzeburgesch', true),
('lg', 'Ganda', true),
('LG', 'Ganda', true),
('li', 'Limburgan; Limburger; Limburgish', true),
('LI', 'Limburgan; Limburger; Limburgish', true),
('ln', 'Lingala', true),
('LN', 'Lingala', true),
('lo', 'Lao', true),
('LO', 'Lao', true),
('lt', 'Lithuanian', true),
('LT', 'Lithuanian', true),
('lu', 'Luba-Katanga', true),
('LU', 'Luba-Katanga', true),
('lv', 'Latvian', true),
('LV', 'Latvian', true),
('mg', 'Malagasy', true),
('MG', 'Malagasy', true),
('mh', 'Marshallese', true),
('MH', 'Marshallese', true),
('mi', 'Maori', true),
('MI', 'Maori', true),
('mk', 'Macedonian', true),
('MK', 'Macedonian', true),
('ml', 'Malayalam', true),
('ML', 'Malayalam', true),
('mn', 'Mongolian', true),
('MN', 'Mongolian', true),
('mr', 'Marathi', true),
('MR', 'Marathi', true),
('ms', 'Malay', true),
('MS', 'Malay', true),
('mt', 'Maltese', true),
('MT', 'Maltese', true),
('my', 'Burmese', true),
('MY', 'Burmese', true),
('na', 'Nauru', true),
('NA', 'Nauru', true),
('nb', 'Bokmål, Norwegian; Norwegian Bokmål', true),
('NB', 'Bokmål, Norwegian; Norwegian Bokmål', true),
('nd', 'Ndebele, North; North Ndebele', true),
('ND', 'Ndebele, North; North Ndebele', true),
('ne', 'Nepali', true),
('NE', 'Nepali', true),
('ng', 'Ndonga', true),
('NG', 'Ndonga', true),
('nl', 'Dutch; Flemish', true),
('NL', 'Dutch; Flemish', true),
('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian', true),
('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian', true),
('no', 'Norwegian', true),
('NO', 'Norwegian', true),
('nr', 'Ndebele, South; South Ndebele', true),
('NR', 'Ndebele, South; South Ndebele', true),
('nv', 'Navajo; Navaho', true),
('NV', 'Navajo; Navaho', true),
('ny', 'Chichewa; Chewa; Nyanja', true),
('NY', 'Chichewa; Chewa; Nyanja', true),
('oc', 'Occitan (post 1500); Provençal', true),
('OC', 'Occitan (post 1500); Provençal', true),
('oj', 'Ojibwa', true),
('OJ', 'Ojibwa', true),
('om', 'Oromo', true),
('OM', 'Oromo', true),
('or', 'Oriya', true),
('OR', 'Oriya', true),
('os', 'Ossetian; Ossetic', true),
('OS', 'Ossetian; Ossetic', true),
('pa', 'Panjabi; Punjabi', true),
('PA', 'Panjabi; Punjabi', true),
('pi', 'Pali', true),
('PI', 'Pali', true),
('pl', 'Polish', true),
('PL', 'Polish', true),
('ps', 'Pushto; Pashto', true),
('PS', 'Pushto; Pashto', true),
('pt', 'Portuguese', true),
('PT', 'Portuguese', true),
('qu', 'Quechua', true),
('QU', 'Quechua', true),
('rm', 'Romansh', true),
('RM', 'Romansh', true),
('rn', 'Rundi', true),
('RN', 'Rundi', true),
('ro', 'Romanian; Moldavian; Moldovan', true),
('RO', 'Romanian; Moldavian; Moldovan', true),
('ru', 'Russian', true),
('RU', 'Russian', true),
('rw', 'Kinyarwanda', true),
('RW', 'Kinyarwanda', true),
('sa', 'Sanskrit', true),
('SA', 'Sanskrit', true),
('sc', 'Sardinian', true),
('SC', 'Sardinian', true),
('sd', 'Sindhi', true),
('SD', 'Sindhi', true),
('se', 'Northern Sami', true),
('SE', 'Northern Sami', true),
('sg', 'Sango', true),
('SG', 'Sango', true),
('si', 'Sinhala; Sinhalese', true),
('SI', 'Sinhala; Sinhalese', true),
('sk', 'Slovak', true),
('SK', 'Slovak', true),
('sl', 'Slovenian', true),
('SL', 'Slovenian', true),
('sm', 'Samoan', true),
('SM', 'Samoan', true),
('sn', 'Shona', true),
('SN', 'Shona', true),
('so', 'Somali', true),
('SO', 'Somali', true),
('sq', 'Albanian', true),
('SQ', 'Albanian', true),
('sr', 'Serbian', true),
('SR', 'Serbian', true),
('ss', 'Swati', true),
('SS', 'Swati', true),
('st', 'Sotho, Southern', true),
('ST', 'Sotho, Southern', true),
('su', 'Sundanese', true),
('SU', 'Sundanese', true),
('sv', 'Swedish', true),
('SV', 'Swedish', true),
('sw', 'Swahili', true),
('SW', 'Swahili', true),
('ta', 'Tamil', true),
('TA', 'Tamil', true),
('te', 'Telugu', true),
('TE', 'Telugu', true),
('tg', 'Tajik', true),
('TG', 'Tajik', true),
('th', 'Thai', true),
('TH', 'Thai', true),
('ti', 'Tigrinya', true),
('TI', 'Tigrinya', true),
('tk', 'Turkmen', true),
('TK', 'Turkmen', true),
('tl', 'Tagalog', true),
('TL', 'Tagalog', true),
('tn', 'Tswana', true),
('TN', 'Tswana', true),
('to', 'Tonga (Tonga Islands)', true),
('TO', 'Tonga (Tonga Islands)', true),
('tr', 'Turkish', true),
('TR', 'Turkish', true),
('ts', 'Tsonga', true),
('TS', 'Tsonga', true),
('tt', 'Tatar', true),
('TT', 'Tatar', true),
('tw', 'Twi', true),
('TW', 'Twi', true),
('ty', 'Tahitian', true),
('TY', 'Tahitian', true),
('ug', 'Uighur; Uyghur', true),
('UG', 'Uighur; Uyghur', true),
('uk', 'Ukrainian', true),
('UK', 'Ukrainian', true),
('ur', 'Urdu', true),
('UR', 'Urdu', true),
('uz', 'Uzbek', true),
('UZ', 'Uzbek', true),
('ve', 'Venda', true),
('VE', 'Venda', true),
('vi', 'Vietnamese', true),
('VI', 'Vietnamese', true),
('vo', 'Volapük', true),
('VO', 'Volapük', true),
('wa', 'Walloon', true),
('WA', 'Walloon', true),
('wo', 'Wolof', true),
('WO', 'Wolof', true),
('xh', 'Xhosa', true),
('XH', 'Xhosa', true),
('yi', 'Yiddish', true),
('YI', 'Yiddish', true),
('yo', 'Yoruba', true),
('YO', 'Yoruba', true),
('za', 'Zhuang; Chuang', true),
('ZA', 'Zhuang; Chuang', true),
('zh', 'Chinese', true),
('ZH', 'Chinese', true),
('zu', 'Zulu', true),
('ZU', 'Zulu', true);;
