-- Message Function Code Data Insert Statements
-- Generated from UNECE_MessageFunctionCode_D14A.xsd
-- Total records: 65

INSERT INTO message_function_code (code, name, description, category, is_modification, is_original, is_acceptance) VALUES
('1', 'Cancellation', 'Message cancelling a previous transmission for a given transaction.', 'Cancellation', true, false, false),
('2', 'Addition', 'Message containing items to be added.', 'Addition', true, false, false),
('3', 'Deletion', 'Message containing items to be deleted.', 'Deletion', true, false, false),
('4', 'Change', 'Message containing items to be changed.', 'Change', true, false, false),
('5', 'Replace', 'Message replacing a previous message.', 'Replacement', true, false, false),
('6', 'Confirmation', 'Message confirming the details of a previous transmission where such confirmation is required or recommended under the terms of a trading partner agreement.', 'Confirmation', false, false, false),
('7', 'Duplicate', 'The message is a duplicate of a previously generated message.', 'Duplicate', false, false, false),
('8', 'Status', 'Code indicating that the referenced message is a status.', 'Status', false, false, false),
('9', 'Original', 'Initial transmission related to a given transaction.', 'Original', false, true, false),
('10', 'Not found', 'Message whose reference number is not filed.', 'Processing Status', false, false, false),
('11', 'Response', 'Message responding to a previous message or document.', 'Response', false, false, false),
('12', 'Not processed', 'Message indicating that the referenced message was received but not yet processed.', 'Processing Status', false, false, false),
('13', 'Request', 'Code indicating that the referenced message is a request.', 'Request', false, false, false),
('14', 'Advance notification', 'Code indicating that the information contained in the message is an advance notification of information to follow.', 'Notification', false, false, false),
('15', 'Reminder', 'Repeated message transmission for reminding purposes.', 'Other', false, false, false),
('16', 'Proposal', 'Message content is a proposal.', 'Proposal', false, false, false),
('17', 'Cancel, to be reissued', 'Referenced transaction cancelled, reissued message will follow.', 'Cancellation', true, false, false),
('18', 'Reissue', 'New issue of a previous message (maybe cancelled).', 'Cancellation', true, false, false),
('19', 'Seller initiated change', 'Change information submitted by buyer but initiated by seller.', 'Change', true, false, false),
('20', 'Replace heading section only', 'Message to replace the heading of a previous message.', 'Replacement', true, false, false),
('21', 'Replace item detail and summary only', 'Message to replace item detail and summary of a previous message.', 'Replacement', true, false, false),
('22', 'Final transmission', 'Final message in a related series of messages together making up a commercial, administrative or transport transaction.', 'Other', false, false, false),
('23', 'Transaction on hold', 'Message not to be processed until further release information.', 'Other', false, false, false),
('24', 'Delivery instruction', 'Delivery schedule message only used to transmit short-term delivery instructions.', 'Scheduling', false, false, false),
('25', 'Forecast', 'Delivery schedule message only used to transmit long-term schedule information.', 'Scheduling', false, false, false),
('26', 'Delivery instruction and forecast', 'Combination of codes ''24'' and ''25''.', 'Other', false, false, false),
('27', 'Not accepted', 'Message to inform that the referenced message is not accepted by the recipient.', 'Acceptance', false, false, true),
('28', 'Accepted, with amendment in heading section', 'Message accepted but amended in heading section.', 'Change', true, false, false),
('29', 'Accepted without amendment', 'Referenced message is entirely accepted.', 'Change', true, false, false),
('30', 'Accepted, with amendment in detail section', 'Referenced message is accepted but amended in detail section.', 'Change', true, false, false),
('31', 'Copy', 'Indicates that the message is a copy of an original message that has been sent, e.g. for action or information.', 'Original', false, true, false),
('32', 'Approval', 'A message releasing an existing referenced message for action to the receiver.', 'Other', false, false, false),
('33', 'Change in heading section', 'Message changing the referenced message heading section.', 'Change', true, false, false),
('34', 'Accepted with amendment', 'The referenced message is accepted but amended.', 'Change', true, false, false),
('35', 'Retransmission', 'Change-free transmission of a message previously sent.', 'Change', true, false, false),
('36', 'Change in detail section', 'Message changing referenced detail section.', 'Change', true, false, false),
('37', 'Reversal of a debit', 'Reversal of a previously posted debit.', 'Other', false, false, false),
('38', 'Reversal of a credit', 'Reversal of a previously posted credit.', 'Other', false, false, false),
('39', 'Reversal for cancellation', 'Code indicating that the referenced message is reversing a cancellation of a previous transmission for a given transaction.', 'Cancellation', true, false, false),
('40', 'Request for deletion', 'The message is given to inform the recipient to delete the referenced transaction.', 'Deletion', true, false, false),
('41', 'Finishing/closing order', 'Last of series of call-offs.', 'Other', false, false, false),
('42', 'Confirmation via specific means', 'Message confirming a transaction previously agreed via other means (e.g. phone).', 'Confirmation', false, false, false),
('43', 'Additional transmission', 'Message already transmitted via another communication channel. This transmission is to provide electronically processable data only.', 'Addition', true, false, false),
('44', 'Accepted without reserves', 'Message accepted without reserves.', 'Acceptance', false, false, true),
('45', 'Accepted with reserves', 'Message accepted with reserves.', 'Acceptance', false, false, true),
('46', 'Provisional', 'Message content is provisional.', 'Other', false, false, false),
('47', 'Definitive', 'Message content is definitive.', 'Other', false, false, false),
('48', 'Accepted, contents rejected', 'Message to inform that the previous message is received, but it cannot be processed due to regulations, laws, etc.', 'Acceptance', false, false, true),
('49', 'Settled dispute', 'The reported dispute is settled.', 'Dispute', false, false, false),
('50', 'Withdraw', 'Message withdrawing a previously approved message.', 'Deletion', true, false, false),
('51', 'Authorisation', 'Message authorising a message or transaction(s).', 'Other', false, false, false),
('52', 'Proposed amendment', 'A code used to indicate an amendment suggested by the sender.', 'Change', true, false, false),
('53', 'Test', 'Code indicating the message is to be considered as a test.', 'Test', false, false, false),
('54', 'Extract', 'A subset of the original.', 'Original', false, true, false),
('55', 'Notification only', 'The receiver may use the notification information for analysis only.', 'Notification', false, false, false),
('56', 'Advice of ledger booked items', 'An advice that items have been booked in the ledger.', 'Other', false, false, false),
('57', 'Advice of items pending to be booked in the ledger', 'An advice that items are pending to be booked in the ledger.', 'Other', false, false, false),
('58', 'Pre-advice of items requiring further information', 'A pre-advice that items require further information.', 'Notification', false, false, false),
('59', 'Pre-adviced items', 'A pre-advice of items.', 'Notification', false, false, false),
('60', 'No action since last message', 'Code indicating the fact that no action has taken place since the last message.', 'Processing Status', false, false, false),
('61', 'Complete schedule', 'The message function is a complete schedule.', 'Scheduling', false, false, false),
('62', 'Update schedule', 'The message function is an update to a schedule.', 'Scheduling', false, false, false),
('63', 'Not accepted, provisional', 'Not accepted, subject to confirmation.', 'Confirmation', false, false, false),
('64', 'Verification', 'The message is transmitted to verify information.', 'Verification', false, false, false),
('65', 'Unsettled dispute', 'To report an unsettled dispute.', 'Dispute', false, false, false);;

-- End of insert statements
