-- Payment Terms Type Code Data Insert Statements
-- Generated from UNECE_PaymentTermsTypeCode_D14A.xsd
-- Total records: 79

INSERT INTO payment_terms_type_code (code, name, description, category, is_immediate, is_deferred, has_discount) VALUES
('1', 'Basic', 'Payment conditions normally applied.', 'Standard Terms', false, false, false),
('2', 'End of month', 'Payments are due at end of month.', 'Scheduled Payment', false, false, false),
('3', 'Fixed date', 'Payments are due on the fixed date specified.', 'Scheduled Payment', false, false, false),
('4', 'Deferred', 'Payments are deferred beyond the normal due date.', 'Deferred Payment', false, true, false),
('5', 'Discount not applicable', 'Payment terms on which discounts are not applicable.', 'Discount Terms', false, false, false),
('6', 'Mixed', 'Different payment terms negotiated under a documentary credit.', 'Letter of Credit', false, false, false),
('7', 'Extended', 'Payment is extended beyond the normal due date.', 'Deferred Payment', false, true, false),
('8', 'Basic discount offered', 'Payment terms reflect the basic offered discount.', 'Discount Terms', false, false, true),
('9', 'Proximo', 'Occurring in the next month after present.', 'Scheduled Payment', false, false, false),
('10', 'Instant', 'Payment is due on receipt of invoice.', 'Immediate Payment', true, false, false),
('11', 'Elective', 'Payment terms to be chosen by buyer (from options separately advised).', 'Custom Terms', false, false, false),
('12', '10 days after end of month', 'Payment due ten days after end of a calendar month.', 'Scheduled Payment', false, false, false),
('13', 'Seller to advise buyer', 'Seller will advise buyer of payment terms by separate transaction.', 'Other Terms', false, false, false),
('14', 'Paid against statement', 'Payments are to be made against statement.', 'Documentary Payment', false, false, false),
('15', 'No charge', 'Payment terms have no charge.', 'Other Terms', false, false, false),
('16', 'Not yet defined', 'Payment terms are not yet defined.', 'Other Terms', false, false, false),
('17', 'Ultimo', 'Payment is due the end of the current or specified month.', 'Other Terms', false, false, false),
('18', 'Previously agreed upon', 'Payment terms have been previously agreed upon.', 'Other Terms', false, false, false),
('19', 'United States funds', 'The payment terms require the use of United States funds.', 'Other Terms', false, false, false),
('20', 'Penalty terms', 'Payment terms on which penalties apply.', 'Penalty Terms', false, false, false),
('21', 'Payment by instalment', 'Payment terms are based on instalment payments.', 'Installment Payment', false, false, false),
('22', 'Discount', 'Payment terms on which discounts are applicable.', 'Discount Terms', false, false, true),
('23', 'Available by sight payment', 'Payment made at sight.', 'Other Terms', true, false, false),
('24', 'Available by deferred payment', 'Payment made at deferred date.', 'Deferred Payment', false, true, false),
('25', 'Available by acceptance', 'Payment on acceptance.', 'Other Terms', false, false, false),
('26', 'Available by negotiation with any bank', 'Payment made by negotiation with any bank.', 'Other Terms', false, false, false),
('27', 'Available by negotiation with any bank in ...', 'Payment made by negotiation with any bank in a specified location.', 'Other Terms', false, false, false),
('28', 'Available by negotiation by named bank', 'Payment made by negotiation with a specified financial institution.', 'Other Terms', false, false, false),
('29', 'Available by negotiation', 'Payment made by negotiation.', 'Other Terms', false, false, false),
('30', 'Adjustment payment', 'Payment adjusted for outstanding credits or debits.', 'Other Terms', false, false, false),
('31', 'Late payment', 'Payment after due date.', 'Penalty Terms', false, true, false),
('32', 'Advanced payment', 'Payment in advance of due date.', 'Advance Payment', true, false, false),
('33', 'Payment by instalments according to progress (as agreed)', 'Payment by instalments according to progress (as agreed).', 'Installment Payment', false, false, false),
('34', 'Payment by instalments according to progress (to be agreed)', 'Payment by instalments according to progress (to be agreed).', 'Installment Payment', false, false, false),
('35', 'Nonstandard', 'Terms of payment differ from the normal terms.', 'Standard Terms', false, false, false),
('36', 'Tenor payment terms', 'Payment to be made according to bilaterally agreed conditions between buyer and seller.', 'Penalty Terms', false, false, false),
('37', 'Complete payment', 'Payment must be made for complete value and may not be paid in instalments.', 'Installment Payment', false, false, false),
('38', 'Payment terms defined in consolidated invoice', 'Payment terms are specified in a consolidated invoice.', 'Other Terms', false, false, false),
('39', 'Payment upon completion', 'The payment terms require payment upon completion.', 'Other Terms', false, false, false),
('40', 'Partial advance', 'The payment terms require a partial payment in advance of completion.', 'Advance Payment', true, false, false),
('41', 'Consignment', 'The payment terms are that the goods will be paid for when they are sold or consumed.', 'Other Terms', false, true, false),
('42', 'Inter-company account', 'The payment terms involve the use of an inter-company account.', 'Other Terms', false, false, false),
('43', 'Sell by note', 'The payment terms involve a debtor who promises to pay a definite sum of money on demand or at a definite time in the future.', 'Other Terms', false, false, false),
('44', 'Supplier floor plan', 'The payment terms involve payment for merchandise owned by a third party.', 'Other Terms', false, true, false),
('45', 'Contract basis', 'The payment terms are based on a contract with a vendor.', 'Other Terms', false, false, false),
('46', 'Credit controlled', 'The payment terms involve the monitoring of credit by the grantor.', 'Other Terms', false, false, false),
('47', 'Dating given', 'The payment terms in which suppliers may extend seasonal dating.', 'Other Terms', false, false, false),
('48', 'Trade acceptance', 'A trade acceptance is a written acknowledgement of the sale of goods and promise to pay at a definite date and place.', 'Other Terms', false, false, false),
('49', 'Cost plus', 'The payment terms permit reimbursement of costs plus other authorised changes.', 'Other Terms', false, false, false),
('50', 'Letter of credit', 'The payment terms require the use of a letter of credit.', 'Letter of Credit', false, false, false),
('51', 'Lease agreement', 'The payment terms are included in the lease agreement.', 'Other Terms', false, false, false),
('52', 'Cash On Delivery (COD)', 'The payment terms are cash is due on delivery of merchandise.', 'Immediate Payment', true, false, false),
('53', 'Cash by state law', 'The payment terms are dictated by state law requiring payment of cash.', 'Cash/Cheque Payment', false, false, false),
('54', 'Bank transfer', 'The payment terms require the use of bank transfer.', 'Other Terms', false, false, false),
('55', 'Cash on arrival', 'The payment terms require payment by cash on arrival of the goods or services.', 'Cash/Cheque Payment', false, false, false),
('56', 'Cash', 'The payment terms are that payments are made in cash.', 'Cash/Cheque Payment', false, false, false),
('57', 'Cash discount terms apply', 'The payment terms are that a discount is applicable if the payment is made in cash.', 'Discount Terms', false, false, true),
('58', 'Cash with order', 'The payment terms require the payment in cash with placement of the order.', 'Cash/Cheque Payment', false, false, false),
('59', 'Cash per vendor request', 'The payment terms involve a vendor request for payment by cash.', 'Cash/Cheque Payment', false, false, false),
('60', 'Irrevocable letter of credit', 'The payment terms require the use of an irrevocable letter of credit.', 'Letter of Credit', false, false, false),
('61', 'Documents against acceptance', 'The payment terms require acceptance of liability before document transfer.', 'Other Terms', false, false, false),
('62', 'Charge card', 'The payment terms permit the use of a charge card to effect payment.', 'Other Terms', false, false, false),
('63', 'Documents against payment', 'The payment terms require payment before document transfer.', 'Other Terms', false, false, false),
('64', 'Usance bill', 'The payment terms are based on the time allowed by commercial usage for the payment of foreign bills of exchange.', 'Other Terms', false, false, false),
('65', 'Letter of credit at sight', 'The payment terms require the presentation of a letter of credit.', 'Letter of Credit', false, false, false),
('66', 'Secured account', 'The payment terms call for the use of a secured account.', 'Other Terms', false, false, false),
('67', 'Basic commission terms', 'The payment terms call for the use of basic commission terms.', 'Standard Terms', false, false, false),
('68', 'Deposit required', 'The payment terms require a deposit be provided.', 'Advance Payment', true, false, false),
('69', 'Discount with prompt pay', 'The payment terms include a discount when payment is made within a time frame designated as prompt pay.', 'Discount Terms', false, false, true),
('70', 'Discount with advance payment', 'The payment terms include a discount when payment is made in advance.', 'Discount Terms', true, false, true),
('71', 'Certified cheque', 'The payment terms require the use of a certified cheque.', 'Cash/Cheque Payment', false, false, false),
('72', 'Cash against documents', 'The payment terms require cash payment before document transfer.', 'Cash/Cheque Payment', false, false, false),
('73', 'Bill of exchange', 'The payment terms require the use of bill of exchange.', 'Trade Instruments', false, false, false),
('74', 'Progressive discount', 'The payment terms include a progressive discount based on the amount and speed with which payments are made.', 'Discount Terms', false, false, true),
('75', 'Lump sum', 'The payment term requires a lump sum payment.', 'Fixed Payment', false, false, false),
('76', 'Fixed fee', 'The payment term requires a fixed fee payment.', 'Fixed Payment', false, false, false),
('77', 'Promissory note', 'The payment term requires the use of a promissory note as a means of payment.', 'Trade Instruments', false, false, false),
('78', 'Factoring', 'Payment term requires payment being made by the factoring company according to the agreement between buyer, bank and factoring company.', 'Factoring', false, false, false),
('ZZZ', 'Mutually defined', 'A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list.', 'Immediate Payment', false, false, false);

-- End of insert statements
